Implement instant search screen - 5
simpledotorg/simple-android pull request #2272
Opened 2021-01-07 01:57 UTC by msasikanth

https://app.clubhouse.io/simpledotorg/story/2029/implement-instant-search-screen

2021-01-07 09:12 UTC, Honey14 requested changes
Looks good overall. App is crashing when clicked on `Register New Patient`.
Reproduction scenario :
* Click on enter patient's name -> search -> click on register new patient -> crash

Not the expected behaviour :
* Scan BP passport -> Register New patient -> does nothing just closes the sheet -> click on register new patient in `InstantSearchScreen` -> crash 
(Expected behaviour: opening patient entry screen from BpPassportSheet)

2021-01-07 09:14 UTC, msasikanth commented on app/src/test/java/org/simple/clinic/instantsearch/InstantSearchUiRendererTest.kt
> +  fun `when there is no instant search progress state, then hide search progress`() {
This is not a duplicate of it the done state, here we are verifying the initial state when screen/model is first created.

2021-01-07 09:16 UTC, msasikanth commented
> Looks good overall. App is crashing when clicked on `Register New Patient`.
> Reproduction scenario :
> 
> * Click on enter patient's name -> search -> click on register new patient -> crash
> 
> Not the expected behaviour :
> 
> * Scan BP passport -> Register New patient -> does nothing just closes the sheet -> click on register new patient in `InstantSearchScreen` -> crash
>   (Expected behaviour: opening patient entry screen from BpPassportSheet)

Yes, that crash is expected. We are tracking it [here](https://app.clubhouse.io/simpledotorg/story/2209/remove-assertion-error-and-deprecate-setonfocuschangelistener-in-dateofbirthedittext), the story also contains the links to why the crash is happening. 

The BP passport sheet results have been just merged. So I need to add support for it now.

Since this feature is under feature flag, these should be fine. While I am making the final PR, I will enable the feature.

2021-01-07 10:12 UTC, msasikanth commented
Address this [issue ](https://app.clubhouse.io/simpledotorg/story/2209/remove-assertion-error-and-deprecate-setonfocuschangelistener-in-dateofbirthedittext) as well

2021-01-07 11:28 UTC, Honey14 requested changes
Looks good overall. Because of the latest date issue change, adding new blood sugar is not working as expected in the PR but is working in the master. PTAL.

2021-01-07 11:30 UTC, msasikanth commented
> Looks good overall. Because of the latest date issue change, adding new blood sugar is not working as expected in the PR but is working in the master. PTAL.

Can you explain what you mean by not working as expected?

2021-01-07 11:35 UTC, Honey14 commented
> > Looks good overall. Because of the latest date issue change, adding new blood sugar is not working as expected in the PR but is working in the master. PTAL.
> 
> Can you explain what you mean by not working as expected?

Reproduction -> click on add diabetes -> add any rbs -> does not work at all. 
Reason : My bad it's not the date change. Logs don't say much. Can we check what was the last change we made?

2021-01-08 06:40 UTC, Honey14 approved these changes
Looks good

2021-01-08 06:40 UTC, merged