Migrate app to use View Binding instead of Kotlin synthetic view accessors - 12
simpledotorg/simple-android pull request #2313
Opened 2021-01-28 07:24 UTC by janhavisinghh

https://app.clubhouse.io/simpledotorg/story/1828/migrate-app-to-use-view-binding-instead-of-kotlin-synthetic-view-accessors

2021-01-29 08:36 UTC, Honey14 requested changes
Looks good. App is crashing on `OverDueScreen`. PTAL.

Reproduction steps: Click on `Enter Patient's name` and now click back button to come to home page.

2021-01-29 08:48 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/bloodsugar/selection/type/BloodSugarTypeAdapter.kt
> +  lateinit var binding: ListBloodSugarTypeBinding
Can we move this inside `onCreateViewHolder` please?

2021-01-29 08:49 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/bloodsugar/selection/type/BloodSugarTypeAdapter.kt
> +) : RecyclerView.ViewHolder(containerView), LayoutContainer {
Since we are no longer using the Kotlin synthetic view accessors for the adapter, we can drop the `LayoutContainer` implementation here.

2021-01-29 16:22 UTC, janhavisinghh commented
I have solved all the issues, please review and merge @Honey14

2021-02-01 06:18 UTC, Honey14 approved these changes
Looks good

2021-02-01 06:18 UTC, merged