In the progress tab, open the drug stock form inside the app
simpledotorg/simple-android pull request #2468
Opened 2021-03-10 10:19 UTC by Honey14

https://app.clubhouse.io/simpledotorg/story/2224/add-drug-stock-form-to-progress-tab-behind-a-feature-flag

2021-03-10 10:42 UTC, msasikanth requested changes
LGTM left a couple of comments PTAL. There seem to be a couple of issues with this feature, check with Rob to see if those are resolved.

- The back button inside the webview doesn't seem to be working, the button inside the cohort report which is behaving the same way is working fine.
- When we submit drug stock we are getting `500` server error. (Already being tracked on [Slack](https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1615368997234000))

2021-03-10 11:50 UTC, Honey14 commented on CHANGELOG.md
> +- In the progress tab, open the drug stock form inside the app
We're not actually adding an option right? We could already do this but now we are opening it inside the app.

2021-03-10 12:22 UTC, msasikanth commented on CHANGELOG.md
> +- In the progress tab, open the drug stock form inside the app
Nope, this is a new feature that is being added to the app.

2021-03-10 12:24 UTC, msasikanth commented on CHANGELOG.md
> +- In the progress tab, open the drug stock form inside the app
So, adding drug stock is a new feature that is being implemented. It was added to the progress bar webview from the HTML data we are receiving from the server. Opening inside the app is the intended behaviour we wanted with the rollout of this feature.

2021-03-11 00:27 UTC, rsanheim commented on CHANGELOG.md
> +- In the progress tab, open the drug stock form inside the app
> So, adding drug stock is a new feature that is being implemented. It was added to the progress tab webview from the HTML data we are receiving from the server. Opening inside the app is the intended behaviour we wanted with the rollout of this feature.

Should we mention in the Changeling that its gated behind a feature flag? Most users won't see this feature for at least a week or more.

2021-03-11 01:51 UTC, msasikanth commented on CHANGELOG.md
> +- In the progress tab, open the drug stock form inside the app
Currently, it's under the internal section, so we won't add it to the Google Play changelog. Maybe we can move it to the features or changes section once it's available for everyone?

2021-03-11 08:21 UTC, Honey14 commented on CHANGELOG.md
> +- In the progress tab, open the drug stock form inside the app
Makes sense.

2021-03-12 04:38 UTC, msasikanth requested changes
LGTM left one comment PTAL. One pending task is handling go back to the progress page from the drug stock success page.

2021-03-12 04:38 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/home/report/ReportsScreen.kt
> +        val url = request?.url.toString()
Since url can be nullable, calling `toString` will return a literal `null` value. Let's handle the `null` here.

2021-03-12 22:49 UTC, rsanheim commented
> back



> LGTM left one comment PTAL. One pending task is handling go back to the progress page from the drug stock success page.

Let me know if there is something we should do from the server side form to help with this -- it looks like we could use [deep links](https://developer.android.com/training/app-links/deep-linking) from the drug form success page to send a user to the progress tab, assuming we have the configuration correct in the Android app.

2021-03-15 02:31 UTC, msasikanth commented
> > LGTM left one comment PTAL. One pending task is handling go back to the progress page from the drug stock success page.
> 
> Let me know if there is something we should do from the server side form to help with this -- it looks like we could use [deep links](https://developer.android.com/training/app-links/deep-linking) from the drug form success page to send a user to the progress tab, assuming we have the configuration correct in the Android app.

Yep, that's the plan. But first, we need to verify we deep links work if the links are inside the app web views. If it doesn't work that way, we need to figure out a different approach.

2021-03-15 02:33 UTC, rsanheim commented
> Yep, that's the plan. But first, we need to verify we deep links work if the links are inside the app web views. If it doesn't work that way, we need to figure out a different approach.

Sounds good, thanks for the update. I've created a new story to capture the navigation / android side of this work: https://app.clubhouse.io/simpledotorg/story/2929/handle-navigation-and-from-drug-stock-success-page-in-the-android-app.

2021-03-15 09:50 UTC, msasikanth commented
Marking it as WIP, since some changes are needed in this PR and Honey is on leave for the next couple of weeks.

2021-03-16 03:20 UTC, msasikanth commented
Taking over pending work in this PR, since Honey is on leave and this feature needs to be finished on priority.

2021-03-16 05:30 UTC, janhavisinghh commented
@msasikanth I think we should close this PR until @Honey14 is back?

2021-03-16 05:32 UTC, msasikanth commented
> @msasikanth I think we should close this PR until @Honey14 is back?

Nope, I am taking over this PR to finish this feature since it's a priority feature.

2021-03-16 17:42 UTC, rsanheim commented
Adding the back button to hook onto in https://github.com/simpledotorg/simple-server/pull/2151.

2021-03-17 18:10 UTC, janhavisinghh commented
@msasikanth I'm not able to test this feature as I don't see anything in the progress tab. Can you help me with that?

2021-03-17 21:09 UTC, rsanheim commented
> @msasikanth I'm not able to test this feature as I don't see anything in the progress tab. Can you help me with that? Also, can we get on a call tomorrow to get more context about the Progress tab?

Note that you'll need the server side to have the feature flag `drug_stocks_mobile` enabled for the drug stock form to be included in the progress tab HTML.  This is already done on sandbox here: https://api-sandbox.simple.org/flipper/features/drug_stocks_mobile.  

Any power-user account (i.e. admin@simple.org) can add or update feature flags for any of our test environments if you navigate to `[simple-server-url]/flipper`.

2021-03-18 01:44 UTC, msasikanth commented
> @msasikanth I'm not able to test this feature as I don't see anything in the progress tab. Can you help me with that? Also, can we get on a call tomorrow to get more context about the Progress tab?

@janhavisinghh You should be able to see a drug stock report card in the progress tab, if you cannot see it right away try clearing the data and log in again.

![photo_2021-03-18_07-11-36](https://user-images.githubusercontent.com/6140516/111560752-32728e80-87b9-11eb-8275-1b03f95e7a65.jpg)

2021-03-18 06:36 UTC, janhavisinghh submitted a review, later dismissed
LGTM

2021-03-18 06:37 UTC, janhavisinghh commented
/rebase

2021-03-18 06:39 UTC, janhavisinghh submitted a review, later dismissed

2021-03-18 06:53 UTC, janhavisinghh commented
/rebase

2021-03-18 06:54 UTC, janhavisinghh approved these changes

2021-03-18 09:24 UTC, janhavisinghh commented
/rebase

2021-03-18 09:28 UTC, janhavisinghh approved these changes

2021-03-18 09:52 UTC, merged