Refactor `BpPassportSheet` to `ScannedQrCodeSheet`
simpledotorg/simple-android pull request #2564
Opened 2021-04-27 20:48 UTC by janhavisinghh

https://app.clubhouse.io/simpledotorg/story/3207/refactor-bppassportsheet-to-scannedqrcodesheet?vc_group_by=day&ct_workflow=all

2021-04-28 14:11 UTC, Honey14 requested changes
Looks good. Left few comments. PTAL
`Changelog` has also not been updated in the PR.

2021-04-28 14:11 UTC, Honey14 commented on app/src/main/java/org/simple/clinic/bp/assignbppassport/ScannedQrCodeUiRenderer.kt
> +    if (model.identifier.type == Identifier.IdentifierType.IndiaNationalHealthId){
Can we import the package before `IndiaNationalHealthId`. This would help in better readability.

2021-04-28 14:11 UTC, Honey14 commented on app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt
> +      blankBpPassportResults.onNext(BlankScannedQrCodeResultReceived(bpPassportResult))
Rename the event name here i.e `blankBpPassportResults`

2021-04-28 14:11 UTC, Honey14 commented on app/src/main/java/org/simple/clinic/instantsearch/InstantSearchScreen.kt
> +      bpPassportScanResults.onNext(QrCodeScanned.fromResult(scanResult))
Same as above comment for `bpPassportScanResults`

2021-04-29 07:32 UTC, janhavisinghh commented on app/src/main/java/org/simple/clinic/bp/assignbppassport/ScannedQrCodeSheet.kt
> +    fun blankBpPassportResult(result: Succeeded): BlankScannedQRCodeResult {
Created a new commit for this

2021-04-30 10:00 UTC, Honey14 approved these changes
Looks good

2021-04-30 10:13 UTC, merged