Remove old patient search flow
simpledotorg/simple-android pull request #2624
Opened 2021-05-12 07:11 UTC by msasikanth

2021-05-12 12:22 UTC, Honey14 requested changes
Looks good. Left few comments, PTAL

2021-05-12 12:28 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt
>    override fun openPatientSearchScreen(additionalIdentifier: Identifier?) {
Yeah, it's doesn't matter TBH. It's still a patient search, right? Ideally

2021-05-12 14:10 UTC, Honey14 commented on app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt
>    override fun openPatientSearchScreen(additionalIdentifier: Identifier?) {
Yes it is patient search but when we see open `PatientSearchScreen`, it looks like we're opening patient search screen which does not reflect what we're doing here.

2021-05-12 14:19 UTC, Honey14 approved these changes

2021-05-12 14:47 UTC, merged

2021-05-12 14:48 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt
>    override fun openPatientSearchScreen(additionalIdentifier: Identifier?) {
Eh, we don't have 2 searches anymore. So I think it should be fine 😂

2021-05-12 14:49 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt
>    override fun openPatientSearchScreen(additionalIdentifier: Identifier?) {
But if you're concerned with it, I can change it in a different PR.

2021-05-13 05:51 UTC, Honey14 commented on app/src/main/java/org/simple/clinic/home/patients/PatientsTabScreen.kt
>    override fun openPatientSearchScreen(additionalIdentifier: Identifier?) {
No it's okay. I figured only the `screen` part as a suffix made me concerned. `openPatientSearch` seems fine. This makes sense as well.