Update the UI for the `OverdueAppointmentRow`
simpledotorg/simple-android pull request #2716
Opened 2021-06-17 07:51 UTC by msasikanth

https://app.clubhouse.io/simpledotorg/story/3736/update-the-ui-for-the-overdueappointmentrow

2021-06-18 09:02 UTC, msasikanth commented
@vinaysshenoy can you approve these code climate issues, please? There is no avoiding the 5 argument limit here. It's a factory constructor 😅

2021-06-21 13:21 UTC, Honey14 requested changes
Overall looks good. Can you check the android tests? And waiting on Vinay to approve the codeclimate issues

2021-06-21 13:25 UTC, msasikanth commented on app/src/main/res/drawable/ic_overdue_call.xml
> +  android:width="40dp"
That's a normal call icon. This is a call icon inside a circle shape.

2021-06-21 13:55 UTC, Honey14 submitted a review, later dismissed
LGTM. @vinaysshenoy Can you approve the codeclimate issues in this PR?

2021-06-22 05:31 UTC, vinaysshenoy commented
> @vinaysshenoy can you approve these code climate issues, please? There is no avoiding the 5 argument limit here. It's a factory constructor sweat_smile
> 
> One way I thought of avoiding this issue was to use Dagger inject to instead of the clock and date formatter. But didn't want to make the adapter part of Dagger.

Cool. For what it's worth, one of the parameters is a feature flag, so this will eventually get removed anyway,

2021-06-22 05:34 UTC, Honey14 approved these changes

2021-06-22 05:34 UTC, merged