Add `OnlineLookupClass` to abstract the network calls for online lookup
simpledotorg/simple-android pull request #2798
Opened 2021-07-05 07:49 UTC by vinaysshenoy

https://app.clubhouse.io/simpledotorg/story/3948/create-use-case-to-query-the-online-lookup-api-and-fetch-the-medical-record

2021-07-05 11:11 UTC, vinaysshenoy commented
This is a pretty large changeset, but a large portion of it is basically factory code for tests, and mapping code for converting the payload into domain objects, so hopefully shouldn't be too much of a pain to review.

2021-07-06 09:32 UTC, Honey14 requested changes
LGTM. Left one comment. PTAL

2021-07-06 09:39 UTC, vinaysshenoy commented on app/src/sharedTest/java/org/simple/clinic/TestData.kt
> +      cancelReason: AppointmentCancelReason? = AppointmentCancelReason.random(),
The model itself allows it as a nullable field. The `TestData` factory method incorrectly had it defined as a non-nullable parameter.

2021-07-06 09:45 UTC, Honey14 approved these changes
LGTM

2021-07-06 09:45 UTC, merged