Implement showing drug frequency in `EditMedicineScreen` based on the country
simpledotorg/simple-android pull request #3135
Opened 2021-09-07 18:01 UTC by janhavisinghh

https://app.clubhouse.io/simpledotorg/story/4782/implement-showing-drug-frequency-in-editmedicinescreen-based-on-the-country

2021-09-07 18:05 UTC, janhavisinghh commented
/rebase

2021-09-08 11:51 UTC, janhavisinghh commented
Added @Honey14 as a reviewer as @vinaysshenoy is on a leave

2021-09-09 12:56 UTC, Honey14 requested changes
Looks great. Left few comments. PTAL?

2021-09-09 12:56 UTC, Honey14 commented on app/src/test/java/org/simple/clinic/drugs/EditMedicineEffectHandlerTest.kt
> +    val expectedResult = drugFrequencyFactory.provideFields()
We're not testing whether the `drugFrequencyFactory.provideFields()` is returning list of choice items or not. We're just adding the expected list and expecting it to work fine. Can you add this, please?

2021-09-09 12:56 UTC, Honey14 commented on app/src/test/java/org/simple/clinic/drugs/EditMedicineUpdateTest.kt
> +
extra space here.

2021-09-15 08:46 UTC, Honey14 commented
There are some build failures, waiting for Janhavi to push.

2021-09-15 09:03 UTC, janhavisinghh commented
There is some issue happening with jitpack [link](https://jitpack.io/com/github/ben-manes/versions/com.github.ben-manes.versions.gradle.plugin/0.38.0/com.github.ben-manes.versions.gradle.plugin-0.38.0.pom) which is why I'm unable to push currently. Will try again in some time @Honey14

2021-09-15 10:31 UTC, Honey14 approved these changes
LGTM

2021-09-15 10:31 UTC, merged