Implement showing medicine frequency labels depending on the country - Final
simpledotorg/simple-android pull request #3141
Opened 2021-09-09 12:42 UTC by janhavisinghh

Implement showing medicine frequency labels depending on the country in `MedicineFrequencySheet` and `TeleconsultMedicinesView`

2021-09-14 05:05 UTC, Honey14 requested changes
Looks good. Few unit tests are failing and left a few comments. PTAL?

2021-09-14 05:05 UTC, Honey14 commented on app/src/main/java/org/simple/clinic/teleconsultlog/medicinefrequency/MedicineFrequencyModel.kt
> +        medicineFrequency: MedicineFrequency, medicineFrequencyToFrequencyChoiceItemMap: Map<MedicineFrequency?, DrugFrequencyChoiceItem>
Can we format the second parameter in the next line?

2021-09-14 07:26 UTC, janhavisinghh commented on app/src/main/java/org/simple/clinic/teleconsultlog/prescription/medicines/TeleconsultMedicineItem.kt
> +    binding.medicineFrequencyButton.text = frequencyLabel
We are using `DrugFrequencyFactoryModule` to load `drugFrequencyChoiceItems` based on the country the user is in. Also, we are only loading different drug frequency labels based on the country(like `PID` for `Ethiopia`) we are saving drug frequencies based on the common acronyms for it(i.e. BD, TDS, QDS, etc)

2021-09-15 10:34 UTC, Honey14 commented
Cannot test this because of [this](https://simpledotorg.slack.com/archives/CFK2PHJ1L/p1631692063251600) issue. Removing myself as a reviewer for now.

2021-09-16 07:49 UTC, Honey14 requested changes
LGTM. Frequency labels are not changing for Ethiopia in teleconsult view. PTAL

2021-09-17 06:11 UTC, Honey14 commented
/rebase

2021-09-17 06:30 UTC, Honey14 approved these changes
LGTM

2021-09-17 06:42 UTC, merged