Set the cursor in the correct position whenever `CustomDrugEntrySheet` is opened
simpledotorg/simple-android pull request #3188
Opened 2021-09-24 06:02 UTC by janhavisinghh

https://app.shortcut.com/simpledotorg/story/5046/custom-drug-entry-sheet-ui-improvements

2021-09-24 06:02 UTC, janhavisinghh commented
/rebase

2021-09-27 06:51 UTC, Honey14 requested changes
LGTM, left feedback, PTAL

2021-09-27 06:51 UTC, Honey14 commented on app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt
> +    val cursorPosition = if (drug.dosage != null) cursorPositionFromDosage(drug.dosage) else 0
Do we need the to return 0 twice here? `cursorPositionFromDosage` is going to return us 0, can we instead check the nullability inside the function and have one condition (either x position or 0 position. WDYT?

2021-09-27 06:51 UTC, Honey14 commented on app/src/test/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdateTest.kt
> +                    .drugInfoProgressStateLoaded()),
Can we extract the model out for readability?

2021-09-27 06:51 UTC, Honey14 commented on app/src/main/java/org/simple/clinic/drugs/selection/custom/CustomDrugEntryUpdate.kt
> +    val cursorPosition = if (prescription.dosage != null) cursorPositionFromDosage(prescription.dosage) else 0
I see why we have 2 conditions now. Apart from having `cursorPositionFromDosage` usage twice? Is there some other reason that I'm missing? 
If not, can we have one condition for these into their individual functions.

2021-09-27 11:37 UTC, janhavisinghh commented
> Steps to reproduce: New medicine -> type custom med -> click on the dialog -> as soon as start typing we see the mg.

Yes this is the expected behaviour @Honey

2021-09-29 08:44 UTC, Honey14 approved these changes
LGTM

2021-09-29 08:51 UTC, merged