Wire Mobius loop with overdue search screen UI
simpledotorg/simple-android pull request #4019
Opened 2022-06-23 08:18 UTC by janhavisinghh

https://app.shortcut.com/simpledotorg/story/8531/wire-mobius-loop-with-overdue-screen-ui

2022-06-23 08:18 UTC, janhavisinghh commented
Current dependencies on/for this PR:
* master
  * **PR #4018** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4018" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4019** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4019" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/4019?utm_source=stack-comment).

2022-06-24 03:01 UTC, msasikanth requested changes
See inline comments

2022-06-24 03:01 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
>    private val disposable = CompositeDisposable()
<!-- GRAPHITE_METADATA {"trueLocation":{"startLine":56,"endLine":68,"prLink":"https://app.graphite.dev/github/pr/simpledotorg/simple-android/4019"}} -->
<i class='graphite__hidden'>[Re: lines 56 to 68]<br/></i>

The placing of these variable seems odd as it breaks the rest of `Inject` variables. Let's move them to `searchQueryTextChanges` variable? <span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4019?utm_source=unchanged-line-comment">Graphite</a>.</span>

2022-06-24 03:02 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/home/overdue/search/OverdueSearchScreen.kt
> +  override fun showOverdueSearchResults(overdueSearchResults: PagingData<OverdueAppointment>) {
The param name is different from what's defined in the `UiActions` interface. So, there is a lint warning. Let's update the name to resolve it.

2022-06-24 03:24 UTC, msasikanth approved these changes

2022-06-24 03:34 UTC, merged