Update Changelog
simpledotorg/simple-android pull request #4171
Opened 2022-08-11 10:43 UTC by Honey14

2022-08-11 11:47 UTC, Honey14 commented
Current dependencies on/for this PR:
* master
  * **PR #4171** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4171" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/4171?utm_source=stack-comment).

2022-08-12 01:32 UTC, msasikanth commented on CHANGELOG.md
> -- Bump gradle to v7.5.1
This is a different Gradle version. Let's add a new entry for the AGP v7.2.2 update.

2022-08-16 01:51 UTC, msasikanth requested changes
See inline comments

2022-08-16 01:51 UTC, msasikanth commented on CHANGELOG.md
> +- Bump AGP to v7.2.2
I meant as a separate line. We have update Gradle and AGP as well. 

Gradle is updated to v7.5.1
AGP is updated to v7.2.2

2022-08-17 06:50 UTC, janhavisinghh requested changes

2022-08-17 06:50 UTC, janhavisinghh commented on CHANGELOG.md
> +- Bump gradle to v7.5.1
We already have `Bump gradle to v7.5.1` changelog at the top

2022-08-17 07:06 UTC, msasikanth approved these changes

2022-08-17 10:02 UTC, janhavisinghh approved these changes

2022-08-17 10:02 UTC, merged