Add patientId and facilityId columns in CallResult table
simpledotorg/simple-android pull request #4218
Opened 2022-09-09 10:19 UTC by janhavisinghh

https://app.shortcut.com/simpledotorg/story/9058/add-sync-support-for-pulling-overdue-call-results

2022-09-09 10:19 UTC, janhavisinghh commented
Current dependencies on/for this PR:
* master
  * **PR #4218** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4218" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/4218?utm_source=stack-comment).

2022-09-12 03:39 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt
> +        facilityId = appointment.facilityUuid
The appointment facility id is not always the same as the user's current facility. Did we check Prabhanshu to see what we want here?

2022-09-12 03:39 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/overdue/callresult/CallResult.kt
> +        facilityId = appointment.facilityUuid
<!-- GRAPHITE_METADATA {"trueLocation":{"startLine":79,"endLine":100,"prLink":"https://app.graphite.dev/github/pr/simpledotorg/simple-android/4218"}} -->
<i class='graphite__hidden'>[Re: lines 79 to 100]<br/></i>

Same comment as above<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4218?utm_source=unchanged-line-comment">Graphite</a>.</span>

2022-09-12 10:10 UTC, msasikanth requested changes
See inline comments

2022-09-12 10:10 UTC, msasikanth commented on app/src/androidTest/java/org/simple/clinic/storage/migrations/Migration105AndroidTest.kt
> +  fun patient_id_and_facility_id_columns_should_be_added_to_call_result_table() {
Looks like you missed removing facility id from the test name

2022-09-12 11:03 UTC, msasikanth approved these changes

2022-09-12 12:46 UTC, msasikanth approved these changes

2022-09-12 13:09 UTC, merged