Cut a release branch if current date is greater than or equal to expected release date
simpledotorg/simple-android pull request #4236
Opened 2022-09-21 03:52 UTC by msasikanth

2022-09-21 03:52 UTC, msasikanth commented
Current dependencies on/for this PR:
* master
  * **PR #4236** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4236" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/4236?utm_source=stack-comment).

2022-09-21 12:49 UTC, Honey14 requested changes
I'm not sure I understand why creating the release branch everyday helps

2022-09-21 13:23 UTC, msasikanth commented
> I'm not sure I understand why creating the release branch everyday helps

We are not creating it everyday? What I mentioned was there is a safeguard against creating a branch every day.

2022-09-22 06:18 UTC, Honey14 approved these changes

2022-09-22 06:35 UTC, merged