Show notification permission rationale dialog when user doesn’t allow notification permission
simpledotorg/simple-android pull request #4313
Opened 2022-11-04 10:43 UTC by noyize

https://app.shortcut.com/simpledotorg/story/9424/show-notification-permission-rationale-dialog-when-user-doesn-t-allow-notification-permission

2022-11-04 10:43 UTC, noyize commented
Current dependencies on/for this PR:
* master
  * **PR #4313** <a href="https://app.graphite.dev/github/pr/simpledotorg/simple-android/4313" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/simpledotorg/simple-android/4313?utm_source=stack-comment).

2022-11-07 02:12 UTC, msasikanth requested changes
See inline comments

2022-11-07 02:12 UTC, msasikanth commented on app/src/test/java/org/simple/clinic/home/HomeScreenViewEffectHandlerTest.kt
> +class HomeScreenViewEffectHandlerTest {
Let's rename this to `HomeScreenEffectHandlerTest`. View effects are part of effect handler tests

2022-11-07 05:06 UTC, msasikanth approved these changes

2022-11-07 05:13 UTC, merged