Refactor `maestro_tests.yml`
simpledotorg/simple-android pull request #4351
Opened 2022-11-23 03:27 UTC by msasikanth

2022-11-23 12:44 UTC, Honey14 commented
/rebase

2022-11-23 12:45 UTC, Honey14 requested changes
Looks good, can you update changelog, please?

2022-11-23 12:45 UTC, Honey14 commented on .github/workflows/maestro_tests.yml
> +            ./gradlew maestroTests
~Is there a benefit of running via Gradle instead?~ NM, for all future tests. Got it

2022-11-23 13:22 UTC, msasikanth commented
> Looks good, can you update changelog, please?

That was intentional. I wanted to discuss this further whether we should include some of the dev changes like dependency updates and CI changes in CHANGELOG or not.

2022-11-25 07:03 UTC, Honey14 approved these changes

2022-11-25 07:04 UTC, merged