Add column deleted_at to the questionnaire table
simpledotorg/simple-android pull request #4532
Opened 2022-12-23 06:25 UTC by siddh1004

1. Story Link: https://app.shortcut.com/simpledotorg/story/9557/add-sync-resource-for-questionnaire-layout-api
2. Questionnaire table modified by adding deleted_at column (type: String, nullable: true)
3. App database version updated to 107.

2022-12-26 12:29 UTC, Honey14 requested changes
Looks great overall, 2 things.
1. can you update changelog, please?
2. Some tests are failing, can you ptal?

2022-12-26 12:49 UTC, siddh1004 commented
> Looks great overall, 2 things.
> 
> 1. can you update changelog, please?
> 2. Some tests are failing, can you ptal?

changelog file updated

2022-12-27 02:51 UTC, msasikanth commented
It looks like rebasing is not done correctly as well. Please take a look at that as well.

2022-12-28 08:30 UTC, Honey14 approved these changes

2022-12-28 08:30 UTC, merged