Monthly screening report fixes
simpledotorg/simple-android pull request #4602
Opened 2023-03-15 06:30 UTC by siddh1004

https://app.shortcut.com/simpledotorg/story/10211/monthly-screening-form-android-fixes

2023-03-15 07:30 UTC, olttwa requested changes

2023-03-15 07:30 UTC, olttwa commented on app/src/main/java/org/simple/clinic/questionnaire/Questionnaire.kt
>      fun getAllQuestionnaires(): List<Questionnaire>
```suggestion
    fun getAll(): List<Questionnaire>
```

2023-03-15 07:30 UTC, olttwa commented on app/src/main/java/org/simple/clinic/questionnaire/Questionnaire.kt
> +    fun getQuestionnaireByType(type: QuestionnaireType): Flowable<Questionnaire>
```suggestion
    fun getByQuestionnaireType(type: QuestionnaireType): Flowable<Questionnaire>
```

2023-03-15 07:30 UTC, olttwa commented on app/src/main/java/org/simple/clinic/questionnaire/Questionnaire.kt
> +    fun getQuestionnaireByTypeImmediate(type: QuestionnaireType): Questionnaire
```suggestion
    fun getByQuestionnaireTypeImmediate(type: QuestionnaireType): Questionnaire
```

2023-03-15 07:30 UTC, olttwa commented on app/src/main/java/org/simple/clinic/monthlyscreeningreports/form/compose/QuestionnaireInputField.kt
> +      content.remove(inputFieldComponentData.linkId)
```suggestion
      content.[inputFieldComponentData.linkId] = null
```

2023-03-15 07:30 UTC, olttwa commented on app/src/main/java/org/simple/clinic/monthlyscreeningreports/form/compose/QuestionnaireInputField.kt
> +      content.remove(inputFieldComponentData.linkId)
This will require changing Content map from `string<>Any` to `string<>NullableAny`

2023-03-15 09:12 UTC, olttwa requested changes

2023-03-16 08:19 UTC, siddh1004 commented on app/src/main/java/org/simple/clinic/questionnaireresponse/QuestionnaireResponse.kt
> +    fun getByQuestionnaireType(type: QuestionnaireType, currentFacilityId: UUID): Flowable<List<QuestionnaireResponse>>
@olttwa https://app.shortcut.com/simpledotorg/story/10224/when-the-user-clears-a-pre-filled-value-then-set-content-key-to-null I need to dig into this as right now, the room library automatically removes the key from map when the value is null

2023-03-16 08:40 UTC, olttwa approved these changes

2023-03-16 09:06 UTC, olttwa approved these changes

2023-03-21 06:56 UTC, olttwa approved these changes

2023-03-21 07:30 UTC, olttwa commented on app/src/main/java/org/simple/clinic/monthlyscreeningreports/form/compose/QuestionnaireInputField.kt
> +  }
```suggestion
  } else
```

2023-03-21 10:59 UTC, olttwa approved these changes

2023-03-21 11:10 UTC, merged