Add patient reassignment eligibility status view
simpledotorg/simple-android pull request #4922
Opened 2024-04-25 10:53 UTC by siddh1004

2024-04-25 10:54 UTC, siddh1004 commented
https://app.shortcut.com/simpledotorg/story/12443/show-patient-eligibility-status-in-the-ui

2024-05-03 06:17 UTC, msasikanth requested changes

2024-05-03 06:17 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/patient/RecentPatient.kt
Looks like the commit message is moved to commit description. PTAL

2024-05-03 06:17 UTC, msasikanth commented on app/src/main/res/drawable/ic_facility_reassignment.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
This icon frame doesn't match the one in the design. We need to download the icon and frame, instead of just the icon glyph.

2024-05-03 07:19 UTC, msasikanth approved these changes

2024-05-03 07:26 UTC, merged