Add CVD Risk Calculation sheet
simpledotorg/simple-android pull request #5155
Opened 2024-12-13 12:28 UTC by siddh1004

https://app.shortcut.com/simpledotorg/story/14050/save-cv-risk-score-json-model-to-database

2025-01-06 07:22 UTC, msasikanth requested changes
Left few comments PTAL

2025-01-06 07:22 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +      bmi: Double? = null
I think a `Float` precision should be enough for BMI

2025-01-06 07:22 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +      cvdRiskData: CVDRiskCalculationSheet?,
If I understand correctly, this sheet data won't change from patient to patient right? Why don't we pass this as dependency to this class and use it here instead of passing it to function everywhere we call it? 🤔

2025-01-06 07:22 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +      in Int.MIN_VALUE..119 -> "120-"
Do we get "120 -" from server? Why not just send it as "<=120", similar to how we have "180+"? Doesn't that make more sense, wdyt?

2025-01-06 07:22 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +            in Double.MIN_VALUE..19.9 -> "20-"
Same comment as the sbp min variable

2025-01-06 07:22 UTC, msasikanth commented on app/src/test/java/org/simple/clinic/cvdrisk/CVDRiskCalculatorTest.kt
> +class CVDRiskCalculatorTest {
Nice work on tests 👍🏾

2025-01-06 07:22 UTC, msasikanth commented on app/src/test/java/org/simple/clinic/cvdrisk/CVDRiskCalculatorTest.kt
> +  private val testData = TestData.cvdRiskCalculationSheet()
This variable should be `cvdRiskCalculationSheet` instead of `testData`

2025-01-06 07:22 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskModule.kt
> +  fun cvdRiskCalculationSheet(moshi: Moshi, configReader: ConfigReader): CVDRiskCalculationSheet? {
So, this happens on the main thread. Since this JSON is large, I am worried that it might cause ANR. How about we load it lazily and in a different thread and place where we use it?

2025-01-08 07:10 UTC, siddh1004 commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculationSheet.kt
> +    val sbp: String,
Done.

2025-01-08 07:14 UTC, siddh1004 commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +      bmi: Double? = null
Done

2025-01-08 07:15 UTC, siddh1004 commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +      in Int.MIN_VALUE..119 -> "120-"
We get this from server as "120-", so we can't change it to "<=120"

2025-01-08 07:15 UTC, siddh1004 commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +            in Double.MIN_VALUE..19.9 -> "20-"
We get this from server as "20-", so we can't change it to "<=20"

2025-01-08 07:15 UTC, siddh1004 commented on app/src/test/java/org/simple/clinic/cvdrisk/CVDRiskCalculatorTest.kt
> +class CVDRiskCalculatorTest {
Thanks

2025-01-08 07:16 UTC, siddh1004 commented on app/src/test/java/org/simple/clinic/cvdrisk/CVDRiskCalculatorTest.kt
> +  private val testData = TestData.cvdRiskCalculationSheet()
Done

2025-01-08 07:25 UTC, msasikanth commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +      in Int.MIN_VALUE..119 -> "120-"
Yeah, I understand that. I was talking about updating the spec from server and in the app.

2025-01-08 08:06 UTC, siddh1004 commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculationSheet.kt
> +data class CVDRiskCalculationGenderSheet(
I have renamed it to `CVDRiskCategory`

2025-01-08 08:06 UTC, siddh1004 commented on app/src/main/java/org/simple/clinic/cvdrisk/CVDRiskCalculator.kt
> +      cvdRiskData: CVDRiskCalculationSheet?,
Done.

2025-01-08 09:07 UTC, msasikanth approved these changes

2025-01-08 09:09 UTC, merged